name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true

      - name: Show Go env
        run: |
          go version
          go env

      - name: Verify go.mod is tidy
        run: |
          #go mod tidy
          git diff --exit-code || (echo "Run 'go mod tidy' and commit changes" && exit 1)

      - name: Check formatting (gofmt)
        run: |
          DIFF=$(gofmt -s -l .)
          if [ -n "$DIFF" ]; then
            echo "The following files need gofmt -s:" && echo "$DIFF" && exit 1
          fi

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build -trimpath -ldflags "-s -w" ./cmd/gocomicwriter
